backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "faq"
    label: "Faq"
    folder: "src/pages/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "faq" }
      - { label: "Question", name: "question", widget: string }
      - { label: "Position", name: "position", widget: number }
      - { label: "Answer", name: "body", widget: "markdown" }
  - name: "testimonial"
    label: "Testimonial"
    folder: "src/pages/testimonials"
    create: true
    slug: "{{slug}}-{{role}}-{{company}}"
    fields:
      - { label: "Author", name: "author", widget: string }
      - { label: "Company", name: "company", widget: string }
      - { label: "Role", name: "role", widget: string }
      - { label: "Quote", name: "body", widget: "markdown" }
      - { label: "Avatar", name: "avatar", widget: image }
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "templateKey", widget: "hidden", default: "PostPage" }
      - { label: "Title", name: "title", widget: string }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "IndexPage",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Title, name: title, widget: string },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "SimplePage",
            }
          - { label: "Title", name: "title", widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/privacy.md"
        label: "Privacy"
        name: "privacy"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "SimplePage",
            }
          - { label: "Title", name: "title", widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/terms.md"
        label: "Terms & Conditions"
        name: "terms"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "SimplePage",
            }
          - { label: "Title", name: "title", widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/refund.md"
        label: "Refund policy"
        name: "refund"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "SimplePage",
            }
          - { label: "Title", name: "title", widget: string }
          - { label: "Body", name: "body", widget: "markdown" }
